first/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from first import views
from django.conf.urls.static import static
# SET THE NAMESPACE!
app_name = 'first'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    path('', views.home, name='home'),
    path('<int:note_id>/', views.detail, name='detail'),
    path('add_note/',views.add_note_button, name = 'add_note_button'),
    path('post/new/<username>/', views.post_new, name='post_new'),
    
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    path('calendar/', views.calendar_button, name='calendar_button'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    
    path('folders/', views.folder, name='folder'),
    
    path('upload/', views.upload, name='upload'),
    path('files/', views.book_list, name='book_list'),
    path('files/upload/', views.upload_book, name='upload_book'),
    path('files/<int:pk>/', views.delete_book, name='delete_book')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whonote/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from first import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls')),
    url(r'^$', views.index,name='index'),
    url(r'^special/', views.special,name='special'),
    url(r'^first/', include('first.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),  
]

whynote-project/whynote-project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('whynote.urls')),
    path('grappelli/', include('grappelli.urls')),   #grappelli URLS
    path('admin/', admin.site.urls)
]

whynote/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'whynote'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:note_id>/', views.detail, name='detail'),
    path('add_note/',views.add_note_button, name = 'add_note_button'),
    path('post/new/', views.post_new, name='post_new'),
    
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    path('calendar/', views.calendar_button, name='calendar_button'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    
    path('folders/', views.folder, name='folder'),
    
    path('tab_settings/', views.tab_set, name='tab_set'),
    
    path('upload/', views.upload, name='upload'),
    path('books/', views.book_list, name='book_list'),
    path('books/upload/', views.upload_book, name='upload_book'),
    path('books/<int:pk>/', views.delete_book, name='delete_book')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whynote-project/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()
    last_name = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    action_flag = models.PositiveSmallIntegerField()

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class WhynoteComment(models.Model):
    author_name = models.CharField(max_length=70)
    comment_text = models.CharField(max_length=200)
    note = models.ForeignKey('WhynoteNote', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'whynote_comment'


class WhynoteNote(models.Model):
    note_title = models.CharField(max_length=200)
    note_text = models.TextField()
    public_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'whynote_note'


class WhynotePost(models.Model):
    title = models.CharField(max_length=70)
    text = models.CharField(max_length=1024)

    class Meta:
        managed = False
        db_table = 'whynote_post'

whynote-project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<font color = black style = "font-family: 'Oswald', 'Futura', sans-serif;">
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 

 <link rel="stylesheet" href="{% static 'sitemaster.css' %}" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 <title>{% block title %}Whynote{% endblock %}</title>

</head>
<style type="text/css">
  
  .sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

a{
  text-decoration: none;
}
</style>


<header>
<div class="shadow p-1 mb-5 bg-dark" id="navbar_top">
  <nav class="mb-1 navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
  <a class="navbar-brand" href="{%url 'whynote:home'%}" style="font-size: 30px">Whynote</a>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto text-right">
     <li class="nav-item">
      <a class="nav-link" href="{% url 'whynote:calendar_button' %}">Calendar</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'whynote:upload' %}">Files</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class=" dropdown-item" href = "{% url 'whynote:tab_set' %}">Text and background</a>
        </div>
      </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'whynote:book_list' %}">About us</a>
    </li>
  </ul>
  </div>
  </div>
  </nav>
  </div>
</header>

{% block style %}
  <style type="text/css">
  </style>
 {% endblock %}

<body>
 {% block content %}

 {% endblock%}

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script>
if ($(window).width() > 992) {
  $(window).scroll(function(){  
     if ($(this).scrollTop() > 40) {
        $('#navbar_top').addClass("fixed-top");
        // add padding top to show content behind navbar
        $('body').css('padding-top', $('.navbar').outerHeight() + 'px');
      }else{
        $('#navbar_top').removeClass("fixed-top");
         // remove padding top from body
        $('body').css('padding-top', '0');
      }   
  });
}
</script>
</body>
</font>
</html>

whynote-project/templates/book_list.html
{% extends 'base.html' %}

{% block content %}

  <div class="container w-50">
  	<h2>Books</h2>
  	<p><a href="{% url 'whynote:upload_book' %}" class="btn btn-warning">
	  Upload book
	</a></p>
	<table class="table table-hover">
	  <thead>
		<tr>
			<th>Cover</th>
			<th>Title</th>
			<th>Author</th>
			<th>Download</th>
			<th>Delete</th>
		</tr>
	  </thead>
	  <tbody>
	  	{% for book in books %}
	  	<tr>
	  	  <td>
	  	  	{% if book.cover %}
	  	  	<img src="{{ book.cover.url }}" alt="{{ book.title }}" style="width: 100px">
	  	  	{% else %}
	  	  	<span class="text-muted">No cover</span>
	  	  	{% endif %}
	  	  </td>
	  	  <td>{{ book.title }}</td>
	  	  <td>{{ book.author }}</td>
	  	  <td>
	  	  	<a href="{{ book.pdf.url }}" class="btn btn-warning">
	  	  		Download
	  	  	</a>
	  	  </td>
	  	  <td>
	  	  	<form method="POST" action="{% url 'whynote:delete_book' book.pk %}">
	  	  	  {% csrf_token %}
	  	  	  <button type="submit" class="btn btn-danger">Delete</button>
	  	  	</form>
	  	  </td>
	  	</tr>
	  	{% endfor %}
	  </tbody>
	</table>
    </div>

{% endblock %}

whynote-project/templates/calendar.html
{% extends 'base.html' %}

{% block style %}
<style type="text/css">
table {
  table-layout: fixed;
  word-wrap: break-word;
}

.calendar {
  caption-side: top;
  padding: 0;
}
.month {
  padding: 1rem;
  background: lightgray;
  text-align: center;
}

.month ul {
  margin: 0;
  padding: 0;
  list-style-type: none;
}
.month ul li {
  color: white;
  font-size: 20px;
  text-transform: uppercase;
  letter-spacing: 3px;
}
.month .prev {
  float: left;
  padding-top: 10px;
}

.month .next {
  float: right;
  padding-top: 10px;
}
#calendar>tbody>tr>td {
  padding: 0;
}

#calendar .card, #calendar .card-header{
  border: 0;
}

 #calendar .card-header{
  background-color: lightgray;
}

#calendar .active .card-header {
  background: #ffc107;
}

.card{
  height: 150px;
}

.card-text{
    font-size: 19px;
    text-align: left;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
}

.dayurl > a{
  text-decoration: none;
  color: black;
}

.list-numbered {
  size: 17px;
  list-style: none;
  counter-reset: line;
}

.list-numbered > li {
  position: relative;
  margin-bottom: 1.5em;
}

.list-numbered > li:before {
  position: absolute;
  left: -2.25em;
  display: inline-block;
  width: 17px;
  height: 17px;
  margin-right: 0.5em;
  background-color:  #ffc107;
  border-radius: 50%;
  color: black;
  text-align: center;
  line-height: 1.25em;
  counter-increment: line;
  content: counter(line);
}

a{
  text-decoration: none;
  color: black;
}

</style>
{% endblock %}

{% block content %}

  <div class="container" style="max-width: 1100px">
    <div class="row" style="padding: 15px">
      <div class="col-3 text-left">
        <a class="btn-lg btn-warning text-dark" href="{% url 'whynote:calendar' %}?{{prev_month}}" style="margin-right: 8px; text-decoration: none;">
          < </a>

        <a class="btn-lg btn-warning text-dark" href="{% url 'whynote:calendar' %}?{{next_month}}" style="text-decoration: none;"> ></a>
      </div>
      <div class="col-6 text-center">
        <h2> Calendar </h2>
      </div>
      <div class="col-3 text-right">
        <a class="btn-lg btn-warning text-dark" href="{% url 'whynote:event_new' %}" style="text-decoration: none;">New</a>
        <a class="btn-lg btn-warning text-dark" href="{% url 'whynote:calendar' %}" style="text-decoration: none;">Today</a>
      </div>
    </div>

    <div class="table-responsive" id="calDiv">
      {{calendar}}
    </div>
  </div>
{% endblock %}

whynote-project/templates/event.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <!--link rel="stylesheet" href="{% static 'calendarstyle.css' %}" type="text/css"-->
  <title>WhyEvent</title>
</head>
<style>
body {
font-family: Montserrat, sans-serif;
background-color: #E8E8E8
}

a {
  text-decoration: none;
  color: #17a2b8;
}

.btn{
  border-radius: 5px;
  border: 7px solid #1abc9c;
  padding: 10px;
  outline: none;
  text-transform: uppercase;
  text-align: center;
  color: black;
  background-color: transparent;
  box-shadow: 0 0 0 0;
}

.left{
  font-size: 16px;
  width: 100px;
  margin: 10px;
  float: left;
}

.right{
  font-size: 14px;
  width: 110px;
  margin: 15px;
  float: right;
}
.form {
  margin: auto;
}

.form input, .form select, .form textarea {
  border-radius: 5px;
  border: 1px solid #1abc9c;
  outline: none;
  background: none;
  padding: 5px;
  width: 100%;
}

</style>

<body bgcolor=#E8E8E8>
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'whynote:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2">
      <button type="submit" class="btn btn-info right">
        Save Event 
      </button>
    </td></tr>
  </table>
</form>
</body>
</html>

whynote-project/templates/folders.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

whynote-project/templates/home.html
{% extends 'base.html' %}

{% block content %}

  <div class = "container">
    <div class = "row">
      <div class="col-2"><h4>Folders</h4></div>
      <div class="col-9">
        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active text-info" id="nav-all-tab" data-toggle="tab" href="#nav-all" role="tab" aria-controls="nav-all" aria-selected="true">All</a>
            <a class="nav-item nav-link text-info" id="nav-profile-tab" data-toggle="tab" href="#nav-f2" role="tab" aria-controls="nav-f2" aria-selected="false">Folder 2</a>
          </div>
      </nav>
      </div>
      <div class="col-1"><a class="btn btn-warning" href="{% url 'whynote:post_new' %}">Create</a></div>
    </div>
    <div class="row" >
      <div class="col-2"></div>
      <div class="col-9 main">
        <div class="tab-content" id="nav-tabContent" >
          <div class="tab-pane fade show active" id="nav-all" role="tabpanel" aria-labelledby="nav-all-tab" >
        <div class="row row-cols-1 row-cols-md-3"  >

          {% for nt in latest_notes %}
            <div class="col mb-3">
              <div class="shadow-sm p-1 mb-5">
              <div class="card h-50 border-dark mb-3 text-dark" style="max-width: 15rem;">
                <div class="card-body">
                  <h5 class="card-title"> 
                    <a class="text-info" href="{% url 'whynote:detail' nt.id %}">{{nt.note_title}} </a>
                  </h5>
                  <p class="card-text">{{nt.preview}}</p>
                  </div>
                  <div class="card-footer bg-transparent border-dark">{{nt.public_date}}</div>
              </div>
              </div>
            </div>
          {% endfor %}
        </div>

      </div>
      <div class="tab-pane fade" id="nav-f2" role="tabpanel" aria-labelledby="nav-f2-tab">Hi</div>
      </div>
      </div>
      <div class="col-1"></div>
    </div>

  </div>

  <footer class="page-footer">
    <div class="footer container">
      <div class="row">
        <div class="col-6 footer-child copyright  ">
        <p class="text-right">WhyNote © 2020 All Rights Reserved</p>
        </div>
        <div class="col-6 footer-child footer-links ">
          <p class="text-right">Privacy Policy FAQ</p>
          <div>
            <small >Made by WhyNote Team
            </small>
        </div>
      </div>
    </div>
  </div>
  </footer>

</html>
{% endblock %}

whynote-project/templates/text_and_background_settings.html
{% extends 'base.html' %}

{% block content %}
    <h1>View settings</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

whynote-project/templates/upload.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
  <div class="btn btn-warning left">
    <a href="{% url 'whynote:home' %}" class="text-decoration-none text-dark">Back</a>
  </div>
  <div class="btn btn-warning left">
    <a href="{% url 'whynote:book_list' %}" class="text-decoration-none text-dark">Books</a>
  </div>
</div>

  <div class="uploadtitle">
	<h2>Your files</h2>	
  </div>

  <div class="container my-4">
  	<div class="row justify-content-center">
	<form method="post" enctype="multipart/form-data" class="fileform">
	{% csrf_token %}
	  <div class="input-group mb-3">
  		<div class="custom-file">
	      <input type="file" name="document" class="custom-file-input" id="inputGroupFile02">
	      <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">
	        Choose file
	      </label>
		</div>
		<button type="submit" class="btn btn-warning">Upload</button>
	  </div>
	</form>
    </div>
  </div>

	<div class="files">
		{% if url %}
		  <p>Uloaded file: <a href="{{ url }}">{{url}}</a></p>
		{% endif %}
	</div>

{% endblock %}