first/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from first import views
from django.conf.urls.static import static
# SET THE NAMESPACE!
app_name = 'first'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    path('', views.home, name='home'),
    path('<int:note_id>/', views.detail, name='detail'),
    path('add_note/',views.add_note_button, name = 'add_note_button'),
    path('post/new/<username>/', views.post_new, name='post_new'),
    
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    path('calendar/', views.calendar_button, name='calendar_button'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    
    path('folders/', views.folder, name='folder'),
    
    path('upload/', views.upload, name='upload'),
    path('files/', views.book_list, name='book_list'),
    path('files/upload/', views.upload_book, name='upload_book'),
    path('files/<int:pk>/', views.delete_book, name='delete_book')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whonote/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from first import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls')),
    url(r'^$', views.index,name='index'),
    url(r'^special/', views.special,name='special'),
    url(r'^first/', include('first.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),  
]

whynote-project/whynote-project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('whynote.urls')),
    path('grappelli/', include('grappelli.urls')),   #grappelli URLS
    path('admin/', admin.site.urls)
]

templates/add_note.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<font color = black style = "font-family: 'Oswald', 'Futura', sans-serif;">
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 

 <link rel="stylesheet" href="{% static 'sitemaster.css' %}" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 <title>{% block title %}Whynote{% endblock %}</title>

</head>
<style type="text/css">
  
  .sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

h1, h2, h3, h4, h5{
	text-align: center;
}

a{
  text-decoration: none;
  color: black;
}
.form {
  margin: auto;
}

.form input, .form select, .form textarea {
  border-radius: 5px;
  border: 1px solid gray;
  margin-bottom: 5px;
  outline: none;
  background: none;
  padding: 5px;
  width: 100%;
</style>


{% block style %}
  <style type="text/css">
  </style>
 {% endblock %}

<body>
<header class="fixed-top page-header">
<div class="shadow p-1 mb-5 bg-dark" id="navbar_top">
  <nav class="navbar navbar-expand-lg navbar-custom navbar-dark bg-dark">
  <div class="container">
  <a class="navbar-brand" href="{% url 'first:home' %}" style="font-size: 30px">Whynote</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon">

                  </span>
            </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
  <ul class="navbar-nav mr-auto text-right">    
          {% if user.is_authenticated %}
            <li class="nav-item"><a class = "nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'first:user_login' %}">Login</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'first:register' %}">Register</a></li>
          {% endif %}
          {% if user.is_authenticated %}
     <li class="nav-item">
      <a class="nav-link" href="{% url 'first:calendar_button' %}">Calendar</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'first:book_list' %}">Files</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href ="#" >Text and background</a>
        </div>
      </li>
      {% endif %}
      <li class="nav-item">
      <a class="nav-link" href="#">About us</a>
    </li>
  </ul>
  </div>
  </div>
  </nav>
  </div>
</header>
<div class = "container" style="padding-top: 110px;">
 {% block content %}

 {% endblock%}
</div>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script type="text/javascript">
    $(document).ready(function() {
    // executes when HTML-Document is loaded and DOM is ready
	console.log("document is ready"); 
	$( ".card" ).hover(
	  function() {
	    $(this).addClass('shadow-lg').css('cursor', 'pointer'); 
	  }, function() {
	    $(this).removeClass('shadow-lg');
	  }
	);
	// document ready  
	});
  </script>
</body>
</font>
</html>

templates/book_list.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
  <div class="container w-50">
  	<h2>Your files</h2>
  	<p><a href="{% url 'first:upload_book' %}" class="btn btn-warning">
	  Upload file
	</a></p>
	<table class="table table-hover">
	  <thead>
		<tr>
			<th>Cover</th>
			<th>Title</th>
			<th>Author</th>
			<th>Download</th>
			<th>Delete</th>
		</tr>
	  </thead>
	  <tbody>
	  	{% for book in books %}
	  	<tr>
	  	  <td>
	  	  	{% if book.cover %}
	  	  	<img src="{{ book.cover.url }}" alt="{{ book.title }}" style="width: 100px">
	  	  	{% else %}
	  	  	<span class="text-muted">No cover</span>
	  	  	{% endif %}
	  	  </td>
	  	  <td>{{ book.title }}</td>
	  	  <td>{{ book.author }}</td>
	  	  <td>
	  	  	<a href="{{ book.pdf.url }}" class="btn btn-warning">
	  	  		Download
	  	  	</a>
	  	  </td>
	  	  <td>
	  	  	<form method="POST" action="{% url 'first:delete_book' book.pk %}">
	  	  	  {% csrf_token %}
	  	  	  <button type="submit" class="btn btn-danger">Delete</button>
	  	  	</form>
	  	  </td>
	  	</tr>
	  	{% endfor %}
	  </tbody>
	</table>
    </div>
{% endif %}
{% endblock %}

templates/calendar.html
{% extends 'base.html' %}

{% block style %}
<style type="text/css">
table {
  table-layout: fixed;
  word-wrap: break-word;
}

.calendar {
  caption-side: top;
  padding: 0;
}

.month {
  padding: 1rem;
  background: lightgray;
  text-align: center;
}

.month ul {
  margin: 0;
  padding: 0;
  list-style-type: none;
}
.month ul li {
  color: white;
  font-size: 20px;
  text-transform: uppercase;
  letter-spacing: 3px;
}
.month .prev {
  float: left;
  padding-top: 10px;
}

.month .next {
  float: right;
  padding-top: 10px;
}
#calendar>tbody>tr>td {
  padding: 0;
}

#calendar .card, #calendar .card-header{
  border: 0;
}

 #calendar .card-header{
  background-color: lightgray;
}

#calendar .active .card-header {
  background: #ffc107;
}

.card{
  height: 170px;
  overflow: auto;
}

.card-text{
  font-size: 19px;
  text-align: left;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.dayurl > a{
  text-decoration: none;
  color: black;
}

.list-numbered {
  size: 17px;
  list-style: none;
  counter-reset: line;
}

.list-numbered > li {
  position: relative;
  margin-bottom: 1.5em;
}

.list-numbered > li:before {
  position: absolute;
  left: -2.25em;
  display: inline-block;
  width: 17px;
  height: 17px;
  margin-right: 0.5em;
  background-color:  #ffc107;
  border-radius: 50%;
  color: black;
  text-align: center;
  line-height: 1.25em;
  counter-increment: line;
  content: counter(line);
}

a{
  text-decoration: none;
  color: black;
}

</style>
{% endblock %}

{% block content %}
  <div class="row" style="padding: 15px">
    <div class="col-4">
      <!-- <nav aria-label="">
       <ul class="pagination">
         <li class="page-item">
            <a class="page-link text-info bg-light" href="{% url 'first:calendar' %}?{{prev_month}}">Previous</a>
          </li>
          <li class="page-item">
             <a class="page-link text-dark bg-light" href="{% url 'first:calendar' %}">Today</a>
          </li>
          <li class="page-item">
            <a class="page-link text-info bg-light" href="{% url 'first:calendar' %}?{{next_month}}">Next</a>
          </li>
        </ul>
      </nav> -->
      <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-outline-warning">
         <a class="text-dark text-decoration-none" href="{% url 'first:calendar' %}?{{prev_month}}">Previous</a>
        </label>
        <label class="btn btn-outline-warning">
          <a class="text-dark text-decoration-none" href="{% url 'first:calendar' %}">Today</a>
        </label>
        <label class="btn btn-outline-warning">
          <a class="text-dark text-decoration-none" href="{% url 'first:calendar' %}?{{next_month}}">Next</a>
        </label>
      </div>
    </div>
    <div class="col-4">
        <h2> Calendar </h2>
      </div>
      <div class="col-4">
        <div class="d-flex justify-content-end">
        <a href="{% url 'first:event_new' %}" class="btn btn-outline-warning text-dark text-decoration-none" role="button">New event</a>
      </div>
      </div>
      </div>

    <div class="table" id="calDiv">
      {{calendar}}
    </div>
  </div>
{% endblock %}

templates/event.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table mb-4">
    {{ form }}
    <tr><td colspan="2" class="text-right">
      <button type="submit" name="create_event" class="btn btn-warning">
        Save Event 
      </button>
    </td></tr>
    <div class="d-flex justify-content-end">
    <button type="submit" name="delete_event" class="btn btn-danger">Delete</button>
    </div>
  </table>
</form>
{% endif %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
  {% if user.is_authenticated %}
  <div class = "container">
    <div class="row">
      <div class="col-11">
      <h3 style="text-align: right;">Hello, {{user.username}} </h3>
    </div>
    </div>
    <div class = "row">
      <div class="col-2"><h4>Folders</h4></div>
      <div class="col-9">
        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active text-info" id="nav-all-tab" data-toggle="tab" href="#nav-all" role="tab" aria-controls="nav-all" aria-selected="true">All</a>
            <a class="nav-item nav-link text-info" id="nav-profile-tab" data-toggle="tab" href="#nav-f2" role="tab" aria-controls="nav-f2" aria-selected="false">Folder 2</a>
          </div>
      </nav>
      </div>
      <div class="col-1"><a class="btn btn-warning" href="{% url 'first:post_new' user.username %}">Create</a></div>
    </div>
    <div class="row" >
      <div class="col-2"></div>
      <div class="col-9 main">
        <div class="tab-content" id="nav-tabContent" >
          <div class="tab-pane fade show active" id="nav-all" role="tabpanel" aria-labelledby="nav-all-tab" >
        <div class="row row-cols-1 row-cols-md-3"  >

          {% for nt in latest_notes %}
            <div class="col mb-3">
              <div class="shadow-sm p-1 mb-5">
              <div class="card h-50 border-dark mb-3 text-dark" style="max-width: 15rem;">
                <div class="card-body">
                  <h5 class="card-title"  style="text-align: left;"> 
                    <a class="text-info" href="{% url 'first:detail' nt.id %}">{{nt.note_title}} </a>
                  </h5>
                  <p class="card-text">{{nt.preview}}</p>
                  </div>
                  <div class="card-footer bg-transparent border-dark">{{nt.public_date}}</div>
              </div>
              </div>
            </div>
          {% endfor %}
        </div>

      </div>
      <div class="tab-pane fade" id="nav-f2" role="tabpanel" aria-labelledby="nav-f2-tab">Hi</div>
      </div>
      </div>
      <div class="col-1"></div>
    </div>

  </div>

  <footer class="page-footer">
    <div class="footer container">
      <div class="row">
        <div class="col-6 footer-child copyright  ">
        <p class="text-right">Whynote © 2020 All Rights Reserved</p>
        </div>
        <div class="col-6 footer-child footer-links ">
          <p class="text-right">Privacy Policy FAQ</p>
          <div>
            <small >Made by Whynote Team
            </small>
        </div>
      </div>
    </div>
  </div>
  </footer>

{% else %}
<div class="card card-image" style="background-image: url(https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1355&q=80);">

  <div class="text-white text-center rgba-stylish-strong py-5 px-4">
    <div class="py-5">
      <!-- Content -->
      <h1 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Welcome to Whynote</strong></h1>
      <p class="mx-5 mb-5">You can use this website to create notes, manage time and keep files in one place. Try it now! <br> Please, 
    <a href="{% url 'first:register'%}" class="badge badge-warning">register</a> to get start.
   Already have an account? <a href="{% url 'first:user_login'%}" class="badge badge-warning">Log in</a></p>
      <a class="btn btn-outline-warning btn-md">About us</a>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    {% if user.is_authenticated %}
        <h2>Here is site for authenticated users of whynote </h2>
        
    {% else %}
        <h2>Here is site for not authenticated WHOnoters</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/innote.html
{% extends 'base.html' %}

{% block title%}{{note.note_title}}{% endblock %}

{% block content %}
<h2 style="font-family: Montserrat">{{note.note_title}}</h2>
<div class="container">
<p style="font-family: Montserrat">{{note.note_text}}</p>

<em style="font-family: Montserrat">{{note.public_date}}</em>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
	  <div class="col-5">
	  	<div class="jumbotron">
	      <h1>Login here:</h1>
			<form method="post" action="{% url 'first:user_login' %}">
	          {% csrf_token %}
	          <div class="form-group">
	            <label for="username">Username:</label>
	            <input type="text" name="username" class="form-control" placeholder="Username">
	          </div>
	          <div class="form-group">
				<label for="password">Password:</label>
	            <input type="password" name="password" class="form-control" placeholder="Password">
	        </div>
			  <input type="submit" class="btn btn-outline-warning text-dark" name="" value="Login">
			</form>
		</div>
	  </div>
    </div>
  </div>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      <div class="row justify-content-md-center">
        <div class="col-9">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h2 class="display-4">Register Here</h2>
        <p class="lead">Just fill out the form.</p>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          <button type="submit" class="btn btn-outline-warning text-dark mb-2 left">Register</button>
        </form>
      {% endif %}
    </div>
    </div>
    </div>
  </div>
{% endblock %}

templates/upload.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
  <div class="btn btn-warning left">
    <a href="{% url 'first:home' %}" class="text-decoration-none text-dark">Back</a>
  </div>
  <div class="btn btn-warning left">
    <a href="{% url 'first:book_list' %}" class="text-decoration-none text-dark">Books</a>
  </div>
</div>

  <div class="uploadtitle">
	<h2>Your files</h2>	
  </div>

  <div class="container my-4">
  	<div class="row justify-content-center">
	<form method="post" enctype="multipart/form-data" class="fileform">
	{% csrf_token %}
	  <div class="input-group mb-3">
  		<div class="custom-file">
	      <input type="file" name="document" class="custom-file-input" id="inputGroupFile02">
	      <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">
	        Choose file
	      </label>
		</div>
		<button type="submit" class="btn btn-warning">Upload</button>
	  </div>
	</form>
    </div>
  </div>

	<div class="files">
		{% if url %}
		  <p>Uloaded file: <a href="{{ url }}">{{url}}</a></p>
		{% endif %}
	</div>

{% endblock %}

templates/upload_book.html
{% extends 'base.html' %}

{% block content %}

	<h2>Upload pdf-file</h2>

	<div class="container my-4">
  	  <div class="row justify-content-center">
	    <form method="post" enctype="multipart/form-data">
	      <table class="table table-borderless table-sm">
		  	{% csrf_token %}
	        <tr><td class="form-group">
	        	{{ form }}
	        </td></tr>
	        <tr><td>
	        <button type="submit" class="btn btn-warning">Upload</button>
	        </td></tr>
	      </table>
	   </form>
      </div>
    </div>

{% endblock %}